import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { observeBody } from '@/lib/domObserver';
import { Clock3, Pause, Play, RefreshCw, Truck, Warehouse } from 'lucide-react';
import { loadDeliveryRunCatalog,loadDeliveryRunLocations,loadDeliveryRunStops,loadDeliveryRunTimeline,type DeliveryRunCatalogRow,type DeliveryRunStopHistoryRow,type DeliveryRunTimelineRow } from '@/data/repositories/runHistory';
import type { DriverLocationSample } from '@/data/repositories/driverLocation';
import { WAREHOUSE } from '@/domain/driverRun';

const W=900,H=470,PAD=52;
function n(value:unknown){const parsed=Number(value);return Number.isFinite(parsed)?parsed:0;}
function date(value?:string|null){return value?new Date(value).toLocaleString('en-AU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—';}
function useHost(){const[host,setHost]=useState<HTMLElement|null>(null);useEffect(()=>observeBody(()=>{const active=Array.from(document.querySelectorAll<HTMLButtonElement>('.sidebar-nav button')).some(b=>b.classList.contains('active')&&b.textContent?.trim()==='Delivery');if(!active){setHost(null);return;}const parent=document.querySelector<HTMLElement>('.desktop-content > .workspace-stack');if(!parent){setHost(null);return;}let mount=parent.querySelector<HTMLElement>('.delivery-run-history-mount');if(!mount){mount=document.createElement('section');mount.className='delivery-run-history-mount';parent.append(mount);}setHost(mount);}),[]);return host;}
function projector(stops:DeliveryRunStopHistoryRow[],samples:DriverLocationSample[]){const points=[{lat:WAREHOUSE.lat,lng:WAREHOUSE.lng},...stops.filter(s=>typeof s.latitude==='number'&&typeof s.longitude==='number').map(s=>({lat:s.latitude!,lng:s.longitude!})),...samples.map(s=>({lat:s.latitude,lng:s.longitude}))];const minLat=Math.min(...points.map(p=>p.lat)),maxLat=Math.max(...points.map(p=>p.lat)),minLng=Math.min(...points.map(p=>p.lng)),maxLng=Math.max(...points.map(p=>p.lng));const span=Math.max(maxLat-minLat,maxLng-minLng,.01);return(lat:number,lng:number)=>({x:PAD+(.06+(lng-minLng)/span*.88)*(W-PAD*2),y:PAD+(.06+(maxLat-lat)/span*.88)*(H-PAD*2)});}
function statusTone(status:string){return status==='COMPLETED'||status==='DELIVERED'?'good':status==='FAILED'?'danger':status==='IN_PROGRESS'?'blue':'neutral';}
function Content(){const[catalog,setCatalog]=useState<DeliveryRunCatalogRow[]>([]);const[selectedKey,setSelectedKey]=useState('');const[stops,setStops]=useState<DeliveryRunStopHistoryRow[]>([]);const[timeline,setTimeline]=useState<DeliveryRunTimelineRow[]>([]);const[samples,setSamples]=useState<DriverLocationSample[]>([]);const[index,setIndex]=useState(0);const[playing,setPlaying]=useState(false);const[error,setError]=useState('');const[loading,setLoading]=useState(false);
  async function loadCatalog(){setError('');try{const rows=await loadDeliveryRunCatalog();setCatalog(rows);setSelectedKey(k=>k||`${rows[0]?.business_day}|${rows[0]?.run_code}`);}catch(r){setError(r instanceof Error?r.message:String(r));}}
  useEffect(()=>{void loadCatalog();},[]);const selected=useMemo(()=>catalog.find(r=>`${r.business_day}|${r.run_code}`===selectedKey)||catalog[0],[catalog,selectedKey]);
  useEffect(()=>{if(!selected)return;let active=true;setLoading(true);Promise.all([loadDeliveryRunStops(selected.business_day,selected.run_code),loadDeliveryRunTimeline(selected.business_day,selected.run_code),loadDeliveryRunLocations(selected.business_day,selected.route_id)]).then(([a,b,c])=>{if(!active)return;setStops(a);setTimeline(b);setSamples(c);setIndex(Math.max(0,c.length-1));setPlaying(false);setError('');}).catch(r=>active&&setError(r instanceof Error?r.message:String(r))).finally(()=>active&&setLoading(false));return()=>{active=false;};},[selected?.business_day,selected?.run_code]);
  useEffect(()=>{if(!playing||samples.length<2)return;const timer=window.setInterval(()=>setIndex(current=>{if(current>=samples.length-1){setPlaying(false);return current;}return current+1;}),650);return()=>window.clearInterval(timer);},[playing,samples.length]);
  const visible=samples.slice(0,index+1);const project=projector(stops,visible);const warehouse=project(WAREHOUSE.lat,WAREHOUSE.lng);const points=visible.map(s=>({...project(s.latitude,s.longitude),sample:s}));const path=points.map(p=>`${p.x},${p.y}`).join(' ');const current=points[points.length-1];
  return <section className="run-history-shell"><header><div><span>DELIVERY RUN ARCHIVE</span><h2>Run history and replay</h2><p>Select Run A, B, C or any later run. Historical route state and GPS samples are read-only and remain separate.</p></div><div><select value={selectedKey} onChange={e=>setSelectedKey(e.target.value)}>{catalog.map(run=><option key={`${run.business_day}-${run.run_code}`} value={`${run.business_day}|${run.run_code}`}>{run.business_day} · Run {run.run_code} · {run.run_status}</option>)}</select><button type="button" onClick={()=>void loadCatalog()}><RefreshCw size={15}/> Refresh</button></div></header>{error?<div className="run-history-error">{error}</div>:null}
  {selected?<><section className="run-history-metrics"><div><strong>Run {selected.run_code}</strong><span>{selected.business_day}</span></div><div><strong>{selected.released_stops}</strong><span>released stores</span></div><div><strong>{selected.delivered_stops}</strong><span>delivered</span></div><div><strong>{selected.failed_stops}</strong><span>failed</span></div><div><strong>{selected.location_samples}</strong><span>GPS samples</span></div><div className={`run-tone-${statusTone(selected.run_status)}`}><strong>{selected.run_status}</strong><span>{selected.route_id}</span></div></section>
  <section className="run-history-grid"><div className="run-replay"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Historical delivery route replay"><rect width={W} height={H} className="run-map-bg"/><polyline points={path} className="run-replay-path"/><g transform={`translate(${warehouse.x} ${warehouse.y})`} className="run-warehouse"><rect x="-15" y="-15" width="30" height="30" rx="6"/><text y="5" textAnchor="middle">W</text></g>{stops.map(stop=>{const p=typeof stop.latitude==='number'&&typeof stop.longitude==='number'?project(stop.latitude,stop.longitude):{x:W/2,y:H/2};return <g key={stop.order_id} transform={`translate(${p.x} ${p.y})`} className={`run-stop run-stop-${stop.stop_status.toLowerCase()}`}><title>{stop.store_name} · {stop.stop_status}</title><circle r="9"/><text y="24" textAnchor="middle">{stop.store_name.slice(0,18)}</text></g>;})}{points.map((point,i)=><circle key={point.sample.id} cx={point.x} cy={point.y} r={i===points.length-1?10:4} className={i===points.length-1?'run-driver-current':'run-driver-sample'}/>)}</svg><div className="run-replay-controls"><button type="button" disabled={samples.length<2} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Replay'}</button><input type="range" min="0" max={Math.max(0,samples.length-1)} value={Math.min(index,Math.max(0,samples.length-1))} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}}/><strong>{current?date(current.sample.captured_at):'No GPS samples'}</strong></div></div>
  <aside className="run-history-side"><section><h3><Truck size={16}/> Stops</h3>{stops.map(stop=><article key={stop.order_id}><span>{stop.stop_number}. {stop.box_code||'—'}</span><div><strong>{stop.store_name}</strong><small>{stop.address||stop.order_number||stop.order_id}</small></div><em>{stop.stop_status}</em></article>)}{!stops.length?<p>No stop snapshot found.</p>:null}</section><section><h3><Clock3 size={16}/> Timeline</h3>{timeline.map((event,i)=><article key={`${event.event_type}-${event.event_at}-${i}`}><time>{date(event.event_at)}</time><div><strong>{event.event_type.replace(/_/g,' ')}</strong><small>{event.order_id||event.actor||selected.route_id}</small></div></article>)}</section></aside></section></>:<p className="run-history-empty">No historical delivery run has been recorded yet.</p>}{loading?<div className="run-history-loading">Loading historical run…</div>:null}<footer><Warehouse size={14}/> Archive data is read-only. A run is separated by business day and run code, so Run A and Run B are never joined.</footer></section>;
}
export function DeliveryRunHistory(){const host=useHost();return host?createPortal(<Content/>,host):null;}
